#!/bin/bash

#SherLocked
source ~/.bash_profile
#TODO's
#@change app name so each team has respective app name on device

#Inputs
#1 = team number/name
#2 = round number
#--NOT NEEDED url and port
#3 = url
#4 = port 

cd android/app
sed_string="s/org.mitre.ctf.sherlocked/org.mitre.ctf.sherlocked.team$1round$2/g"
mv build.gradle build.gradle.old
sed $sed_string build.gradle.old > build.gradle
rm -r build.gradle.old

#debug
cat build.gradle

#Set Up Server Text file
echo SETTING server.txt ...
if [ -f src/main/assets/server.txt ] ; then
rm src/main/assets/server.txt
fi
port=3000
let "port += $1"
echo 10.0.1.26:$port >> src/main/assets/server.txt

#
#build app - options: assemble, assembleDebug, assembleRelease
# Create Unsigned APK app/build/outputs/apk/app-release-unsigned.apk
cd ..
./gradlew assembleRelease 
#DEBUG
#adb install app/build/outputs/apk/app-debug.apk
#
#reset the gradle for next run
cd app
sed_string="s/org.mitre.ctf.sherlocked.team$1round$2/org.mitre.ctf.sherlocked/g"
mv build.gradle build.gradle.old
sed $sed_string build.gradle.old > build.gradle
rm -r build.gradle.old
#cd ..

#NOT NEEDED ANYMORE
#cd back to Challenge Dir - to copy port into sherlocked_backend.py
#cd ..
#sed_string="s/5000/$4/g"
#sed $sed_string sherlocked_backend.py_tpl > sherlocked_backend.py
#cd SherLocked

#TODO
#Create key, sign unsigned apk, align, copy apk and install
#Do we want to install the apk's to the emulators then let them download? 

#cd app
#create key for team$-round$
yes | keytool -genkey -v -keystore team$1-round$2-keystore.keystore -alias team$1Round$2 -keyalg RSA -keysize 2048 -validity 10000 -keypass password -storepass password

#sign APK with key
mv build/outputs/apk/app-release-unsigned.apk ./team$1Round$2SherLocked-signed.apk

echo password | jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore team$1-round$2-keystore.keystore ./team$1Round$2SherLocked-signed.apk team$1Round$2

#align
zipalign -v 4 ./team$1Round$2SherLocked-signed.apk ./team$1Round$2SherLocked.apk

#copy apk to challenge dir
cp ./team$1Round$2SherLocked.apk ../team$1Round$2SherLocked.apk
rm team$1Round$2SherLocked-signed.apk
rm team$1Round$2SherLocked.apk
cd ..
#adb install ./team$1SherLocked.apk



